### ISSUE TITLE
Play2.5+scalikejdbc2.5において、手順漏れ

### ISSUE THREAD

**Issue by yu-ishicawa** [bizreach/play2-hands-on#12]
http://bizreach.github.io/play2-hands-on/play2.5-scalikejdbc2.5/preparation_of_db.html

こちらのページにて、`build.sbt`に`scalikejdbcSettings`を追加する手順が漏れていました。

手順に追加をお願い致します。

**Comment by takezoe** [comment]
@yu-ishicawa ご指摘ありがとうございます。修正してみました。こんな感じでいかがでしょうか？

**Comment by yu-ishicawa** [comment]
はい、大丈夫です！対応ありがとうございます。
