### ISSUE TITLE
playframeworkテンプレートとハンズオンの想定したバージョンが異なりエラーが起きる

### ISSUE THREAD

**Issue by habroptilus** [bizreach/play2-hands-on#14]
ハンズオンを用いて学習を進めていましたが、
2ページ目のプロジェクトの作成部分で、指示通り
sbt new playframework/play-scala-seed.g8 
を実行するとバージョン2.6のテンプレートが作成されてしまいます。
このままsbt run を実行すると
abstractControllerが見つからないというエラーが発生してしまい、先に進めなくなってしまいます。

応急処置としてsbt new...を行う際に
sbt new playframework/play-scala-seed.g8  --branch 2.5.x
とバージョンを指定してプロジェクトを作成するという方法をとることでハンズオンは進めることができました。

このような事例がありましたことをご報告します。

**Comment by takezoe** [comment]
ありがとうございます。Playのバージョンアップは考慮できていませんでした。手順に反映しておきます。Play 2.6にも対応させないといけないですね…。
