### ISSUE TITLE
コマンド実行に失敗する

### ISSUE THREAD

**Issue by Swordroot** [bizreach/play2-hands-on#17]
https://github.com/bizreach/play2-hands-on/blob/2199cfbd1d49eb9900742c776f13bceb52159dff/docs/play2.5-scalikejdbc2.5/preparation_of_db.html#L227

当該部分のコマンドをそのまま実行したところうまくいかず、scalikejdbcGen USERS　と　scalikejdbcGen COMPANIES　のようにコマンドを2回に分けてひとつづつモデルを生成したところうまくいきました。お手数をおかけいたしますが、もしそちらでも同じ状態が確認できた場合に修正していただければ幸いです

**Comment by takezoe** [comment]
@Swordroot ありがとうございます。確認してみます。

**Comment by matsutomu** [comment]
scalikejdbcGenAll で全て生成できるので、そちらで修正出してみました。
