### ISSUE TITLE
ユーザー一覧画面のサンプルコード（テンプレート, L2）に誤植がある

### ISSUE THREAD

**Issue by k0h3y** [bizreach/play2-hands-on#20]
ページ: http://bizreach.github.io/play2-hands-on/play2.5-scalikejdbc2.5/implement_user_list.html

正: `@(users: Seq[models.Users])(implicit request: Request[Any])`
誤: `@(users: Seq[models.Accounts])(implicit request: Request[Any])`

**Comment by k0h3y** [comment]
このハンズオンで作っているモデルはAccountsモデルではなく、Usersモデルなので。

**Comment by takezoe** [comment]
@k0h3y ありがとうございます。修正しました。
