### ISSUE TITLE
sbt sbt-versionコマンドが廃止され、sbt sbtVersionに変わっている

### ISSUE THREAD

**Issue by yusukemorita** [bizreach/play2-hands-on#24]
# 問題

ハンズオンの手順の説明で、「プロジェクトの作成」というページで登場するコマンドです。
例（play2.5-slick3.1）：http://bizreach.github.io/play2-hands-on/play2.5-slick3.1/create_project.html

sbtをインストールする手順で実行するコマンドがこのように与えられています。
```
brew update
brew install sbt
```
↓
```
sbt sbt-version
```
しかし、現在`brew install sbt`でインストールされるsbtのバージョン(2018/06/18現在 ver 1.1.6)では`sbt sbt-version`コマンドは廃止されており、代わりに`sbt sbtVersion`コマンドを使います。

# 解決策

ドキュメントに点在する`sbt sbt-version`コマンドを全て修正するプルリクを作らせて頂きたいのですが、よろしいでしょうか？

**Comment by takezoe** [comment]
@yusukemorita 

> ドキュメントに点在するsbt sbt-versionコマンドを全て修正するプルリクを作らせて頂きたいのですが、よろしいでしょうか？

是非お願いします！

**Comment by yusukemorita** [comment]
https://github.com/bizreach/play2-hands-on/pull/25
作成しました！ご確認お願いしますm(_ _)m
