### ISSUE TITLE
「Play2.8 + ScalikeJDBC3.4」の作成

### ISSUE THREAD

**Issue by mado-m** [bizreach/play2-hands-on#35]
初学者にとってScalikeJDBCは扱いやすいが、シェア的にSlickのサンプルも作成する。

**Comment by mado-m** [comment]
Newest version

Scala: 2.13.1
Play: 2.8.0
ScalikeJDBC: 3.4.0
H2: 1.4.200

**Comment by nhiguchi** [comment]
JavaはLTSの11を使う。

**Comment by mado-m** [comment]
play2.5-slick3.1内のslick-codegenは下記を少しカスタマイズしたものみたい。
今回も最新バージョンが使えるように調整してみる。
https://github.com/slick/slick-codegen-example
