### ISSUE TITLE
PUT,DELETEをWebのformから送りたい

### ISSUE THREAD

**Issue by applideveloper** [bizreach/play2-hands-on#6]
HTML の Form は GET/POST 以外をリクエストすることができません。 
現状は、 POST リクエストに hidden 属性で _method パラメータを付与したり、 
submit イベントを JavaScript でフックして、 Ajax で PUT/DELETE リクエストを代行する
などの方法で回避されていますが、
POSTリクエストで、リクエストヘッダに"X-HTTP-Method-Override": "PUT"で、
POSTをPUTで上書きしたりしてるのですが、Playで、RESTfulなAPIを実現するには
どのようにしてformを拡張して、PUT,DELETEを実現してるのでしょうか？
https://github.com/playframework/playframework/issues/5313

Expressだと、method-overrideというライブラリで、formのmethodを_methodパラメータで上書きしています。
https://github.com/expressjs/method-override/blob/master/index.js

```
$.ajax({
  url: "http://localhost:10320/api/Person/4",
  type: "POST",
  data: JSON.stringify(whatever),
  headers: { 
      "Content-Type": "application/json",
      "X-HTTP-Method-Override": "PUT" },
})
```

https://github.com/playframework/playframework/issues/2063

**Comment by takezoe** [comment]
明確に回答できなかったので随分放置してしまっていましたが、Railsのように擬似的にPUTやDELETEとして扱うような機能があるわけでもないのでこれといった方法はないのではないかと思います。自前で工夫されている方もいらっしゃいますね。
http://mashi.hatenablog.com/entry/2014/02/02/171355

最近だとAjaxやSPAを使うことが多いので、そもそもフォームからPUTやDELETEメソッドで送信したいと思うことがあまりないということもあります。

**Comment by mado-m** [comment]
I’m closing this issue because it has been inactive for a few months.
